name: Build Spring Boot App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Maven
      run: mvn clean install --no-transfer-progress

    - name: Build Docker image
      run: |
        docker build -t springboot-app:${{ github.sha }} .

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Tag Docker image
      run: |
        docker tag springboot-app:${{ github.sha }} 715841370482.dkr.ecr.ap-south-1.amazonaws.com/rb-ecr:${{ github.sha }}

    - name: Push Docker image to ECR
      run: |
        docker push 715841370482.dkr.ecr.ap-south-1.amazonaws.com/rb-ecr:${{ github.sha }}

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: springboot-app
        path: target/*.jar
